=== patriot1burke/triplea/triplea/data/games/strategy/engine/xml/game.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT game (map, resourceList, playerList, unitList, gamePlay, production?, attatchmentList? , initialize?)>

<!ELEMENT map (territory+, connection+) >
	<!ELEMENT territory EMPTY>
	<!ATTLIST territory
		name CDATA #REQUIRED
		water (true | false)  "false"
	>
	<!-- connections are two way -->
	<!ELEMENT connection EMPTY>
	<!ATTLIST connection
		t1 CDATA #REQUIRED 
		t2 CDATA #REQUIRED
	>

<!ELEMENT resourceList (resource+) >
	<!ELEMENT resource EMPTY>
	<!ATTLIST resource 
		name ID #REQUIRED
	>

<!ELEMENT unitList (unit+) >
	<!ELEMENT unit EMPTY>
	<!ATTLIST unit 
		name ID #REQUIRED
	>

<!ELEMENT playerList (player+, alliance*) >
	<!ELEMENT player EMPTY>
	<!ATTLIST player
		name ID #REQUIRED
		optional (true | false) "false"
	>
	<!-- alliances are two way -->
	<!ELEMENT alliance EMPTY>
	<!ATTLIST alliance
		player1 IDREF #REQUIRED 
		player2 IDREF #REQUIRED
	>
		
<!ELEMENT gamePlay (delegate+, sequence)>
	<!ELEMENT delegate EMPTY>
	<!-- javaClass must implement Delegate
		 1 instance created per delegate declaraction, ie 1 instance per name -->
	<!ATTLIST delegate
		name ID #REQUIRED
		javaClass CDATA #REQUIRED
	>
	<!-- if no player given, then delegate is initialized with a null player -->
	<!ELEMENT sequence (step+)>
		<!ELEMENT step EMPTY>
		<!ATTLIST step
			name ID #REQUIRED
			delegate IDREF #REQUIRED
			player IDREF #IMPLIED
		>

<!ELEMENT production (productionRule+, productionFrontier+, playerProduction+)>
	<!ELEMENT productionRule (cost+ , result+)>
	<!ATTLIST productionRule 
		name ID #REQUIRED
	>
		<!ELEMENT cost EMPTY>
		<!ATTLIST cost
			resource IDREF #REQUIRED
			quantity CDATA #REQUIRED
		>
		<!ELEMENT result EMPTY>
		<!ATTLIST result
			resourceOrUnit IDREF #REQUIRED
			quantity CDATA #REQUIRED
		>
	<!ELEMENT productionFrontier (frontierRules+)>
	<!ATTLIST productionFrontier
		name ID #REQUIRED
	>
		<!ELEMENT frontierRules EMPTY>
		<!ATTLIST frontierRules 
			name IDREF #REQUIRED
		>
	<!ELEMENT playerProduction EMPTY>
	<!ATTLIST playerProduction
	    player IDREF #REQUIRED
	    frontier IDREF #REQUIRED
	>
	
<!-- attatchments must implement Attatchment -->
<!ELEMENT attatchmentList (attatchment+) >
	<!ELEMENT attatchment (option+)>
	<!ATTLIST attatchment 
		name CDATA #REQUIRED
		attatchTo CDATA #REQUIRED
		javaClass CDATA #REQUIRED
		type (unitType | territory | resource | player)  "unitType"
	>
		<!ELEMENT option EMPTY> 
		<!ATTLIST option
			name CDATA #REQUIRED
			value CDATA #REQUIRED
		>

<!ELEMENT initialize (ownerInitialize?, unitInitialize?, resourceInitialize?) >
	<!ELEMENT ownerInitialize (territoryOwner+) >
		<!ELEMENT territoryOwner EMPTY>
		<!ATTLIST territoryOwner 
			territory CDATA #REQUIRED
			owner IDREF #REQUIRED
		>
	<!ELEMENT unitInitialize (unitPlacement*, heldUnits*) >
		<!-- units are owned by no one if owner isnt set -->
		<!ELEMENT unitPlacement EMPTY>
		<!ATTLIST unitPlacement
			unitType IDREF #REQUIRED
			territory CDATA #REQUIRED
			quantity CDATA #REQUIRED
			owner IDREF #IMPLIED
		>
		<!-- units that have not been placed yet -->
		<!ELEMENT heldUnits EMPTY>
		<!ATTLIST heldUnits 
			unitType IDREF #REQUIRED
			player IDREF #REQUIRED
			quantity CDATA #REQUIRED
		>
	<!ELEMENT resourceInitialize (resourceGiven+) >
		<!ELEMENT resourceGiven EMPTY>
		<!ATTLIST resourceGiven
			player IDREF #REQUIRED
			resource IDREF #REQUIRED
			quantity CDATA #REQUIRED
		>

=== patriot1burke/triplea/triplea/data/games/strategy/engine/xml/GameExample.xml
<?xml version="1.0" ?>
<!DOCTYPE game SYSTEM "game.dtd">

<game>

	<info name="gameExample" version="1.0" />
	
	<loader javaClass="games.strategy.engine.xml.TestGameLoader"/>
		
	
	<map>
		<territory name="canada"/>
		<territory name="us"/>
		<territory name="atlantic" water="true"/>
		<connection t1="canada" t2="us"/>
	</map>
	<resourceList>
		<resource name="gold"/>
		<resource name="silver"/>
	</resourceList>
	<playerList>
		<player name="chretian" optional="true"/>
		<player name="bush" optional="false"/>
		<player name="castro" optional="false"/>
		<alliance player="chretian" alliance="natp"/>
		<alliance player="castro" alliance="natp"/>

	</playerList>
	<unitList>
		<unit name="inf"/>
	</unitList>
	<gamePlay>
		<delegate name="battle" javaClass="games.strategy.engine.xml.TestDelegate"/>
		<delegate name="move" javaClass="games.strategy.engine.xml.TestDelegate"/>
		<sequence>
			<step name="noPlayer" delegate="move" />
			<step name="usMove" delegate="move" player="bush"/>
			<step name="usFight" delegate="battle" player="bush"/>
			<step name="canMove" delegate="move" player="chretian"/>
			<step name="canFight" delegate="battle" player="chretian"/>
		</sequence>
	</gamePlay>
	<production>
		<productionRule name="infForGold">
			<cost resource="gold" quantity="3" />
			<result resourceOrUnit="inf" quantity="1"/>
		</productionRule>
		<productionRule name="infForSilver">
			<cost resource="silver" quantity="5" />
			<result resourceOrUnit="inf" quantity="1"/>
		</productionRule>
		<productionRule name="infForSilverAndGold">
			<cost resource="silver" quantity="1" />
			<cost resource="silver" quantity="1" />
			<result resourceOrUnit="inf" quantity="5"/>
		</productionRule>
		<productionFrontier name="usProd">
			<frontierRules name="infForGold"/>
			<frontierRules name="infForSilver"/>
		</productionFrontier>
		<productionFrontier name="canProd">
			<frontierRules name="infForSilverAndGold"/>
		</productionFrontier>
		<playerProduction player="bush" frontier="usProd" />
		<playerProduction player="chretian" frontier="canProd" />		
	</production> 

	<attatchmentList>
		<attatchment name="infAttatchment" attatchTo="inf" javaClass="games.strategy.engine.xml.TestAttachment" type="unitType">
			<option name="value" value="inf"/>
		</attatchment>
		<attatchment name="resourceAttatchment" attatchTo="gold" javaClass="games.strategy.engine.xml.TestAttachment" type="resource">
			<option name="value" value="gold"/>
		</attatchment>
		<attatchment name="territoryAttatchment" attatchTo="us" javaClass="games.strategy.engine.xml.TestAttachment" type="territory">
			<option name="value" value="us of a"/>
		</attatchment>
		<attatchment name="playerAttatchment" attatchTo="chretian" javaClass="games.strategy.engine.xml.TestAttachment" type="player">
			<option name="value" value="liberal"/>
		</attatchment>
	</attatchmentList>
	<initialize>
		<ownerInitialize>
			<territoryOwner territory="us" owner="bush"/>
			<territoryOwner territory="canada" owner="chretian"/>
		</ownerInitialize>
		<unitInitialize>
			<unitPlacement unitType="inf" territory="canada" quantity="5" owner="chretian"/>
			<unitPlacement unitType="inf" territory="us" quantity="150" owner="bush"/>
			<heldUnits unitType="inf" player="bush" quantity="20"/>
		</unitInitialize>
		<resourceInitialize>
			<resourceGiven player="chretian" resource="gold" quantity="100"/>
			<resourceGiven player="chretian" resource="silver" quantity="200"/>
		</resourceInitialize>
	</initialize>
		


	
</game>
